const planoEstudosData: FuseWikiDataType = {
    title: 'Plano de Estudos',
    url: '/plano-estudos',
    content: [
        'De forma a apoiar os Alunos na componente de matemática, a UAb criou a disciplina opcional de Matemática Preparatória',
        '21002',
        'Álgebra Linear l',
        '21177',
        'Modelação de Sistemas de Informação',
        '21010',
        'Arquitectura de Computadores',
        '21037',
        'Elementos de Probabilidades e Estatística',
        '21173',
        'Introdução à Programação',
        '21082',
        'Matemática Finita',
        '21174',
        'Sistemas Computacionais',
        '21178',
        'Laboratório de Programação',
        '21175',
        'Análise Infinitesimal',
        '21111',
        'Sistemas Operativos',
        '21176',
        'Ética e Práticas de Engenharia',
        '21048',
        'Física Geral',
        '21179',
        'Laboratório de Desenvolvimento de Software',
        '21053',
        'Fundamentos de Bases de Dados',
        '21046',
        'Estruturas de Dados e Algoritmos Fundamentais',
        '21078',
        'Linguagens e Computação',
        '21071',
        'Introdução à Inteligência Artificial',
        '21093',
        'Programação por Objetos',
        '21076',
        'Investigação Operacional',
        '21106',
        'Sistemas em Rede',
        '21077',
        'Linguagens de Programação',
        '21020',
        'Computação Gráfica',
        '21182',
        'Laboratório de Sistemas e Serviços Web',
        '21180',
        'Computação Numérica',
        '21018',
        'Compilação',
        '21103',
        'Sistemas de Gestão de Bases de Dados',
        '21184',
        'Projeto de Engenharia Informática',
        '21062',
        'Gestão de Projetos Informáticos',
        '21097',
        'Raciocínio e Representação do Conhecimento',
        '21110',
        'Sistemas Multimédia',
        '21108',
        'Sistemas Distribuídos',
        '21181',
        'Segurança em Redes e Computadores',
    ],
};

export default planoEstudosData;
