name: Watch Wiki Page

on:
    schedule:
        - cron: '0 0 * * *' # every 24h
    workflow_dispatch:

jobs:
    check-wiki:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Fetch Wiki Page
              run: curl -s "https://wiki.dcet.uab.pt/files/index.php/Categoria:Engenharia_Inform%C3%A1tica" -o wiki.html

            - name: Install dependencies
              run: pip install beautifulsoup4

            - name: Convert HTML to Text
              run: |
                  mkdir -p wiki-watcher-data
                  python3 - << 'EOF'
                  from bs4 import BeautifulSoup
                  with open("wiki.html", "r", encoding="utf-8") as f:
                      html = f.read()
                  soup = BeautifulSoup(html, "html.parser")
                  text = soup.get_text("\n", strip=True)
                  with open("wiki.txt", "w", encoding="utf-8") as f:
                      f.write(text)
                  EOF

            - name: Compare Hash
              id: check
              run: |
                  mkdir -p wiki-watcher-data
                  NEW_HASH=$(sha256sum wiki.txt | awk '{print $1}')
                  echo "new_hash=$NEW_HASH" >> $GITHUB_OUTPUT

                  if [ -f wiki-watcher-data/.last_hash ]; then
                    OLD_HASH=$(cat wiki-watcher-data/.last_hash)
                  else
                    OLD_HASH=""
                  fi

                  if [ "$OLD_HASH" = "" ]; then
                    echo "changed=first_run" >> $GITHUB_OUTPUT
                  elif [ "$NEW_HASH" != "$OLD_HASH" ]; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

                  echo $NEW_HASH > wiki-watcher-data/.last_hash

            - name: Generate Diff
              if: steps.check.outputs.changed == 'true'
              run: |
                  if [ -f wiki-watcher-data/old_wiki.txt ]; then
                    diff -U 0 wiki-watcher-data/old_wiki.txt wiki.txt > changes.diff || true
                  else
                    echo "No previous file to diff against" > changes.diff
                  fi

            - name: Prepare Issue Body
              if: steps.check.outputs.changed == 'true'
              run: |
                  echo "The following changes were detected in the last watch:" > issue.md
                  echo "" >> issue.md
                  echo '```diff' >> issue.md
                  cat changes.diff >> issue.md
                  echo '```' >> issue.md

            - name: Persist hash and snapshot
              if: steps.check.outputs.changed != 'false'
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  cp wiki.txt wiki-watcher-data/old_wiki.txt
                  git add wiki-watcher-data/.last_hash wiki-watcher-data/old_wiki.txt
                  git commit -m "Update wiki watcher data"
                  git push

            - name: Create Issue
              if: steps.check.outputs.changed == 'true'
              uses: peter-evans/create-issue-from-file@v4
              with:
                  title: '[BOT] Changes to the wiki detected'
                  content-filepath: ./issue.md
                  labels: automated
